language: node_js
node_js:
   - '12.6.0'

services:
   - docker

jobs:
   include:
      -  stage: install dependencies
         script:
            - npm install -g @angular/cli@8.2.0
            - npm install
      -  stage: test
         script: ng lint
