language: node_js
node_js:
   - '11.15'

services:
   - docker

jobs:
   include:
      -  stage: install dependencies
         script:
            - npm install -g @angular/cli@7.3.9
            - npm install
      -  stage: test
         script: ng lint
