services:
   - docker

jobs:
   include:
      -  stage: build image
         if: branch != master
         script: docker build . -t my-passwords-space/password-frontend
      -  stage: build image (prod)
         if: branch = master
         script: docker build . -t my-passwords-space/password-frontend --build-arg build_mode=--prod
