language: node_js
node_js:
   - '11.15'

services:
   - docker

jobs:
   include:
      -  stage: install dependencies
         script:
            - npm install -g @angular/cli@7.3.9
            - npm install
      -  stage: lint
         script: ng lint
      -  stage: build image
         if: branch != master
         script: docker build . -t my-passwords-space/password-frontend
      -  stage: build image (prod)
         if: branch = master
         script: docker build . -t my-passwords-space/password-frontend --build-arg build_mode=--prod
