language: node_js
node_js:
   - '12.7.0'

services:
   - docker

jobs:
   include:
      -  stage: install dependencies
         script:
            - npm install -g @angular/cli@7.3.9
            - npm install
      -  stage: lint
         script: ng lint
      -  stage: build image
         if: branch != master
         script: docker build . -t cloud.canister.io:5000/creekorful/password-frontend:$TRAVIS_BUILD_ID
